server:
  port: 10035
  servlet:
    context-path: /shopping-cart

spring:
  application:
    name: shopping_card_api
  profiles:
    active: local
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS SHOPPING_CARDDB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: SHOPPING_CARDDB
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.netflix: ERROR
    org.springframework.ws.client.MessageTracing: TRACE
    org.springframework.ws.server.MessageTracing: TRACE
    org.springframework.aop.interceptor.CustomizableTraceInterceptor: TRACE